# SPDX-FileCopyrightText: 2024 Dom Rodriguez <shymega@shymega.org.uk

# SPDX-License-Identifier: GPL-3.0-only

version = 1
SPDX-PackageName = "nixfigs"
SPDX-PackageSupplier = "Dom Rodriguez <shymega@shymega.org.uk>"
annotations = []
