# Auto-generated using compose2nix v0.2.3-pre.
{ pkgs, lib, ... }:

{
  virtualisation = {
    containers.enable = true;
    # Runtime
    podman = {
      enable = true;
      autoPrune.enable = true;
      defaultNetwork.settings = {
        # Required for container networking to be able to use names.
        dns_enabled = true;
        ipv6_enabled = true;
      };
    };
    oci-containers.backend = "podman";

    # Containers
    oci-containers.containers."mautrix-slack" = {
      image = "dock.mau.dev/mautrix/slack:latest";
      volumes = [
        "/srv/containers/mautrix-slack:/data:rw"
      ];
      ports = [
        "29335:29335/tcp"
      ];
      log-driver = "journald";
      extraOptions = [
        "--network-alias=mautrix-slack"
        "--network=mautrix-slack_default"
        "--add-host=mtx.shymega.org.uk:95.216.172.104"
      ];
    };
  };
  systemd = {
    services = {
      "podman-mautrix-slack" = {
        serviceConfig = {
          Restart = lib.mkOverride 500 "always";
        };
        after = [
          "podman-network-mautrix-slack_default.service"
        ];
        requires = [
          "podman-network-mautrix-slack_default.service"
        ];
        partOf = [
          "podman-compose-mautrix-slack-root.target"
        ];
        wantedBy = [
          "podman-compose-mautrix-slack-root.target"
        ];
      };

      # Networks
      "podman-network-mautrix-slack_default" = {
        path = [ pkgs.podman ];
        serviceConfig = {
          Type = "oneshot";
          RemainAfterExit = true;
          ExecStop = "podman network rm -f mautrix-slack_default";
        };
        script = ''
          podman network inspect mautrix-slack_default || podman network create --ipv6 mautrix-slack_default
        '';
        partOf = [ "podman-compose-mautrix-slack-root.target" ];
        wantedBy = [ "podman-compose-mautrix-slack-root.target" ];
      };
    };

    # Root service
    # When started, this will automatically create all resources and start
    # the containers. When stopped, this will teardown all resources.
    targets."podman-compose-mautrix-slack-root" = {
      unitConfig = {
        Description = "Root target generated by compose2nix.";
      };
      wantedBy = [ "multi-user.target" ];
    };
  };
}
