# SPDX-FileCopyrightText: 2024 Various Authors <generic@example.com>
#
# SPDX-License-Identifier: GPL-3.0-only

sync_response_cache_duration: 200m
presence:
  enabled: true
experimental_features:
  faster_joins: True
